Django/221012/221012/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup", views.signup, name="signup"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("profil/<int:pk>", views.profil, name="profil"),
]

Django/221012/221012/pjt1012/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('accounts.urls')),
]

Django/221012/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path("", views.index, name="index"),
    path("signup", views.signup, name="signup"),
    path("login", views.login, name="login"),
    path("logout", views.logout, name="logout"),
    path("profil/<int:pk>", views.profil, name="profil"),
]

Django/221012/movies/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "movies"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("delete/<int:pk>", views.delete, name="delete"),
    path("search/", views.search, name="search"),
    path("movie_info/", views.movie_info, name="movie_info"),
    path("movie_create/", views.movie_create, name="movie_create"),
    path("genre_search/<str:genre>", views.genre_search, name="genre_search"),
]

Django/221012/pjt1012/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("movies.urls")),
]

Django/221012/221012/article/models.py
from django.db import models

# Create your models here.

Django/221012/movies/models.py
from django.db import models
from django.conf import settings


# Create your models here.
RATE_CHOICES = (
    (1, "★"),
    (2, "★★"),
    (3, "★★★"),
    (4, "★★★★"),
    (5, "★★★★★"),
)
# user_id -> 이게 유니크 속성을 가지고있어서, 여러 키를 가질 수 없었는데,
# 요거를 유저아이디라는 컬럼으로 가져오는게 아니고, 이름을 다른걸로 지정하면,
# 유니크로 오지 않는다.!


class Review(models.Model):
    userkey = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, db_column="userkey"
    )
    title = models.CharField(max_length=30)
    content = models.TextField()
    movie_name = models.CharField(max_length=30)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    grade = models.IntegerField(choices=RATE_CHOICES)


genre_table = (
    ("액션", "액션"),
    ("스릴러", "스릴러"),
    ("코미디", "코미디"),
    ("로맨스", "로맨스"),
    ("SF", "SF"),
    ("드라마", "드라마"),
    ("애니메이션", "애니메이션"),
)


class Movie(models.Model):
    movie_title = models.CharField(max_length=30)
    summary = models.TextField()
    genre = models.CharField(max_length=80, choices=genre_table)
    start_at = models.DateField()

Django/221012/221012/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Huser


class HuserCreateForm(UserCreationForm):
    class Meta:
        model = Huser
        fields = ["username", "email"]

Django/221012/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Huser


class HuserCreateForm(UserCreationForm):
    class Meta:
        model = Huser
        fields = ["username", "email"]

Django/221012/movies/forms.py
from dataclasses import field
from pyexpat import model
from .models import Review, Movie
from django import forms


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["title", "content", "movie_name", "grade"]


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = "__all__"

Django/221012/221012/accounts/views.py
from django.shortcuts import render, redirect
from .forms import HuserCreateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout as as_logout, login as as_login
from .models import Huser

# Create your views here.


def index(request):
    all_date = Huser.objects.all()
    context = {"all_date": all_date}
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = HuserCreateForm(request.POST)
        form.is_valid()
        form.save()
        return redirect("accounts:login")
    else:
        form = HuserCreateForm()
        context = {"form": form}

        return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            as_login(request, form.get_user())
            return redirect("accounts:index")
    else:
        form = form = AuthenticationForm()
    context = {"form": form}

    return render(request, "accounts/login.html", context)


def logout(request):
    as_logout(request)

    return redirect("accounts:index")


def profil(reuqest, pk):
    user = Huser.objects.get(pk=pk)

    context = {
        "user": user,
    }
    return render(reuqest, "accounts/profil.html", context)

Django/221012/221012/article/views.py
from django.shortcuts import render

# Create your views here.

Django/221012/accounts/views.py
from django.shortcuts import render, redirect
from .forms import HuserCreateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout as as_logout, login as as_login
from .models import Huser

# Create your views here.


def index(request):
    all_date = Huser.objects.all()
    context = {"all_date": all_date}
    return render(request, "accounts/index.html", context)


def signup(request):
    if request.method == "POST":
        form = HuserCreateForm(request.POST)
        form.is_valid()
        form.save()
        return redirect("accounts:login")
    else:
        form = HuserCreateForm()
        context = {"form": form}

        return render(request, "accounts/signup.html", context)


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            as_login(request, form.get_user())
            return redirect("accounts:index")
    else:
        form = form = AuthenticationForm()
    context = {"form": form}

    return render(request, "accounts/login.html", context)


def logout(request):
    as_logout(request)

    return redirect("accounts:index")


def profil(reuqest, pk):
    user = Huser.objects.get(pk=pk)

    context = {
        "user": user,
    }
    return render(reuqest, "accounts/profil.html", context)

Django/221012/movies/views.py
from django.shortcuts import render, redirect
from .forms import MovieForm, ReviewForm
from .models import Movie, Review

# Create your views here.


def index(request):
    reviews = Review.objects.all()

    context = {"reviews": reviews}

    return render(request, "movies/index.html", context)


def create(request):
    if request.method == "POST":
        form_R = ReviewForm(request.POST)
        if form_R.is_valid():
            form_R.save(commit=False)
            form_R.userkey = request.user.pk

            form_R.save()

            return redirect("movies:index")
    else:
        form_R = ReviewForm()
    context = {"form_R": form_R}

    return render(request, "movies/create.html", context)


def delete(reuqest, pk):
    Review.objects.get(pk=pk).delete()

    return redirect("movies:index")


def search(request):
    search = request.GET.get("search", "")

    if request.GET.get("keyword") == "1":
        reviews = Review.objects.filter(title__icontains=search)

    elif request.GET.get("keyword") == "2":
        reviews = Review.objects.filter(content__icontains=search)
    else:
        #  request.GET.get("keyword") == 3:
        reviews = Review.objects.filter(movie_name__icontains=search)

    context = {"reviews": reviews}

    return render(request, "movies/index.html", context)


def movie_info(request):
    movies = Movie.objects.all()
    context = {"movies": movies}
    return render(request, "movies/movie_info.html", context)


def movie_create(request):
    if request.method == "POST":
        form_M = MovieForm(request.POST)
        if form_M.is_valid():
            form_M.save()
            return redirect("movies:movie_info")
    else:
        form_M = MovieForm()
    context = {"form_M": form_M}

    return render(request, "movies/movie_create.html", context)


def genre_search(request, genre):
    genre = genre
    movies = Movie.objects.filter(genre=genre)
    context = {"movies": movies}
    return render(request, "movies/movie_info.html", context)

Django/221012/221012/accounts/templates/accounts/index.html
{% extends 'base.html'%}
{%block content%}
<h1>
    인덱스페이지 도착!
</h1>

{% if request.user.is_authenticated %}
<p>{{request.user}}님 환영합니다</p>
<a href="{% url 'accounts:logout' %}">로그아웃</a>

{% else %}
<a href="{% url 'accounts:signup' %}"> 회원가입 </a>

<a href="{% url 'accounts:login' %}"> 로그인 </a>
{%endif%}




<h1>회원목록페이지! </h1>
<div>
    <h4>회원목록</h4>
    <table class="table table-dark table-striped">
        <th>회원번호</th>
        <th>회원이름</th>
        <th>이메일</th>


        {%for user in all_date%}
        <tr>
            <td>{{user.pk}}</td>
            <td><a href="{% url 'accounts:profil' user.pk %}">{{user.username}}</a></td>
            <td>{{user.email}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{%endblock%}

Django/221012/221012/accounts/templates/accounts/login.html
{% extends 'base.html'%}

{%block content%}
{% load django_bootstrap5 %}
<h1>로그인!</h1>


<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {%bootstrap_form form%}



    {% bootstrap_button button_type="submit" content="로그인" %}
    <button type="button" class="btn btn-primary btn "><a class="text-white"
            href="{% url 'accounts:index' %}">돌아가기</a></button>
</form>

{%endblock%}

Django/221012/221012/accounts/templates/accounts/profil.html
{% extends 'base.html' %}




{% block content %}
<h1> {{user.username}}님의 회원정보 </h1>
<div>
    <h4>이름 {{user.username}} </h4>
    <h4>이메일 {{user.email}} </h4>
    <h4>가입날짜 {{user.date_joined}}</h4>
    <h4>마지막 로그인 {{user.last_login}}</h4>

</div>


<button type="button" class="btn btn-primary btn-lg "><a class="text-white"
        href="{% url 'accounts:index' %}">돌아가기</a></button>



{% endblock %}

Django/221012/221012/accounts/templates/accounts/signup.html
{% extends 'base.html'%}

{%block content%}
{% load django_bootstrap5 %}
<h1>회원가입</h1>


<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {%bootstrap_form form%}



    {% bootstrap_button button_type="submit" content="가입" %}
    <button type="button" class="btn btn-primary btn "><a class="text-white"
            href="{% url 'accounts:index' %}">돌아가기</a></button>
</form>

{%endblock%}