Django/220928/pjt0928/pjt0928/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("posts/", include("posts.urls")),
]

Django/220928/pjt0928/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("delete/<int:pk>", views.delete, name="delete"),
]

Django/220928/pjt0928/posts/models.py
from django.db import models

# Create your models here.


class post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()

Django/220928/pjt0928/posts/views.py
from django.shortcuts import render, redirect
from .models import post


# Create your views here.
def index(request):
    # 모든 글 보여주기
    # 1.db에서 모든 글을 불러온다.
    posts = post.objects.all()
    # 2.템플릿에 보내준다
    context = {"posts": posts}
    return render(request, "posts/index.html", context)


def new(request):
    return render(request, "posts/new.html")


def create(request):
    title = request.GET.get("title")
    content = request.GET.get("content")
    post.objects.create(title=title, content=content)
    context = {
        "title": title,
        "content": content,
    }
    return redirect("posts:index")


def delete(request, pk):
    post.objects.get(id=pk).delete()

    return redirect("posts:index")

Django/220928/pjt0928/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">

</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <footer class="text-center p-3 bg-light">create by caretim 220927</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8"
        crossorigin="anonymous"></script>
</body>

</html>

Django/220928/pjt0928/posts/templates/posts/create.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>작성 완료</h1>

    <p>제목: {{ title }}</p>
    <p>내용: {{ content }}</p>
    <a href="{%url 'posts:index'%}"> 돌아가기</a>
</body>

</html>

Django/220928/pjt0928/posts/templates/posts/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>게시판</h1>

    <ul>
        {%for post in posts%}
        <li>글번호 : {{post.id}} 제목:{{post.title}} | 내용: {{post.content}}
            <a href="">[수정]</a>
            <a href="/posts/delete/{{ post.id}}">[삭제]</a>
        </li>

        {%endfor%}
    </ul>

    <a href="{% url 'posts:new' %}"> 새글쓰기</a>

</body>

</html>

Django/220928/pjt0928/posts/templates/posts/new.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    <h1>새글쓰기</h1>

    <form action="{% url 'posts:create' %}">
        제목 :<input type="text" name='title'><br>
        내용 :<input type="text" name='content'>
        <input type="submit">
    </form>
</body>

</html>