Django/221019/articles/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "articles"

urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/delete_comment/", views.delete_comment, name="delete_comment"),
    path("<int:pk>/comment_update/", views.comment_update, name="comment_update"),
]

Django/221019/articles/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    content = models.TextField()


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=80)
    create_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

Django/221019/articles/forms.py
from dataclasses import field
from socket import fromshare
from django import forms
from .models import Article, Comment


class A_Form(forms.ModelForm):
    class Meta:
        model = Article
        fields = [
            "title",
            "content",
        ]


class C_Form(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

Django/221019/articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import A_Form, C_Form
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


def index(request):
    articles = Article.objects.all()
    comment_list = []
    for art in articles:
        comment_list.append(art.comment_set.all())  # 댓글의객체 이걸

    article_info = zip(articles, comment_list)
    context = {"articles": article_info}

    return render(request, "articles/index.html", context)


@login_required
def create(request):
    if request.method == "POST":
        form = A_Form(request.POST)
        if form.is_valid():
            fform = form.save(commit=False)
            fform.user = request.user
            fform.save()
            return redirect("articles:index")
    else:
        form = A_Form()
    context = {
        "form": form,
    }
    return render(request, "articles/create.html", context)


@login_required
def update(request, pk):
    a = Article.objects.get(pk=pk)
    if a.user == request.user:
        if request.method == "POST":
            form = A_Form(request.POST, instance=a)
            if form.is_valid():
                form.save()
                return redirect("articles:detail", pk)
        else:
            form = A_Form(instance=a)
        context = {"form": form}
        return render(request, "articles/create.html", context)
    else:
        return redirect("articles:detail", pk)


@login_required
def delete(request, pk):
    a = Article.objects.get(pk=pk)
    if a.user == request.user:
        Article.objects.get(pk=pk).delete()
        return redirect("articles:index")
    else:
        messages.warning(request, "작성자가 아닙니다.")
        return redirect("articles:index")


def detail(request, pk):
    detail_data = Article.objects.get(pk=pk)
    comment = detail_data.comment_set.all()
    if request.method == "POST":
        form = C_Form(request.POST)
        if form.is_valid():
            a = form.save(commit=False)
            a.article = detail_data
            a.user = request.user
            a.save()
        return redirect("articles:detail", detail_data.pk)
    else:
        form = C_Form()
    context = {
        "detail_data": detail_data,
        "form": form,
        "comment": comment,
    }
    return render(request, "articles/detail.html", context)


@login_required
def comment_update(request, pk):
    comment = Comment.objects.get(pk=pk)
    if comment.user == request.user:
        if request.method == "POST":
            form = C_Form(request.POST, instance=comment)
            if form.is_valid():
                a = form.save(commit=False)
                a.article = comment.article
                a.user = request.user
                a.save()
                return redirect("articles:detail", pk)
        else:
            form = C_Form(instance=comment)
        context = {
            "form": form,
        }
        return render(request, "articles/detail.html", context)
    else:
        return redirect("articles:detail", pk)


@login_required
def delete_comment(request, pk):
    a = Comment.objects.get(pk=pk)
    if a.user == request.user:
        Comment.objects.get(pk=pk).delete()
        return redirect("articles:index")
    else:
        messages.warning(request, "작성자가 아닙니다.")
        return redirect("articles:detail", pk)

Django/221019/articles/templates/articles/create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<h1> 글 작성 </h1>
<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}

    <button type=submit> 완료 </button>
</form>

{% endblock %}

Django/221019/articles/templates/articles/detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<h1> 상세보기 </h1>

{%if detail_data.user == request.user%}
<div>
    <a href="{% url 'articles:update' detail_data.pk  %}">수정</a>
    <a href="{% url 'articles:delete' detail_data.pk  %}">삭제</a>
</div>
{%endif%}
<hr>
<h1>제목:{{detail_data.title}}</h1>
<p>글쓴이:{{detail_data.user}}</p>

<h5>내용:{{detail_data.content}}</h5>




<hr>

<h3>댓글</h3>
{%if comment %}
<p>총 댓글 수 :{{ comment|length }}개 </p>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type=submit> 댓글작성 </button>
</form>
<hr>
{% for c in comment %}

<p>{{c.content}} | <span style="font-size: 10px;">{{c.user}}</span></p>

{%if c.user == request.user %}
<div>
    <a href="{% url 'articles:delete_comment' c.pk %}">삭제</a>
    <a href="{% url 'articles:comment_update' c.pk %}">수정</a>
</div>
{% endif %}
<hr>
{%endfor %}
{% endblock %}

Django/221019/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content %}
<h1> 인덱스페이지 </h1>
<a href="{% url 'articles:create' %}">글쓰기</a>
<hr>
{% for post,comment_count in articles %}

<a href="{% url 'articles:detail' post.pk %}">{{post.title}}</a>
<p>글쓴이 :{{post.user}}</p>
<p> 댓글 수 : {{comment_count|length }}</p>

<hr>
{%endfor%}



{% endblock %}