Django/221017/221017/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "accounts"
urlpatterns = [
    path("", views.index, name="index"),
    path("signup/", views.signup, name="signup"),
]

Django/221017/221017/articles/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "articles"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
]

Django/221017/221017/pj1017/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/221017/articles/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = "articles"
urlpatterns = [
    path("", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),
]

Django/221017/pj1017/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/221017/221017/articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    img = ProcessedImageField(
        upload_to="image/",
        blank=True,
        processors=[ResizeToFill(1000, 300)],
        format="JPEG",
        options={"quality": 100},
    )

Django/221017/articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    img = ProcessedImageField(
        upload_to="image/",
        blank=True,
        processors=[ResizeToFill(1000, 300)],
        format="JPEG",
        options={"quality": 100},
    )

Django/221017/221017/accounts/views.py
from django.shortcuts import render, redirect

# Create your views here.


def index(request):

    return render(request, "accounts/index.html")


def signup(request):

    return render(request, "accounts/signup.html")

Django/221017/221017/articles/views.py
from django.shortcuts import render, redirect
from .form import MakeArticleForm
from .models import Article
from django.contrib import messages

# Create your views here.


def index(request):
    all_date = Article.objects.all()
    context = {"all_date": all_date}

    return render(request, "articles/index.html", context)


def create(request):
    if request.method == "POST":
        form = MakeArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "글이 작성 완료!")

        return redirect("articles:index")
    else:
        form = MakeArticleForm()
    context = {"form": form}

    return render(request, "articles/create.html", context)


def edit(request, pk):
    pick_data = Article.objects.get(pk=pk)
    if request.method == "POST":
        form = MakeArticleForm(request.POST, request.FILES, instance=pick_data)
        if form.is_valid():
            form.save()
            messages.success(request, "글이 수정 완료!")
        return redirect("articles:detail", pick_data.pk)
    else:
        form = MakeArticleForm(instance=pick_data)
    context = {
        "form": form,
        "pick_data": pick_data,
    }

    return render(request, "articles/edit.html", context)


def detail(request, pk):
    detail_data = Article.objects.get(pk=pk)

    context = {"detail_data": detail_data}

    return render(request, "articles/detail.html", context)


def delete(reuqest, pk):
    Article.objects.get(pk=pk).delete()
    return redirect("articles:index")

Django/221017/accounts/views.py
from django.shortcuts import render, redirect
from .models import Huser

# Create your views here.
from django.contrib.auth import login as as_login, logout as as_logout
from django.contrib.auth.forms import AuthenticationForm


def index(request):

    return render(request, "accounts/index.html")


def signup(request):

    return render(request, "accounts/signup.html")


def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request.POST, data=request.POST)
        if form.is_valid():
            as_login(request, form.get_user())
            return redirect("accounts:index")
    else:
        form = AuthenticationForm()
        context = {"form": form}

    return render(request, "accounts/login.html", context)


def logout(request):
    as_logout(request)
    return redirect("articles:index")

Django/221017/articles/views.py
from django.shortcuts import render, redirect
from .form import MakeArticleForm
from .models import Article
from django.contrib import messages


# Create your views here.


def index(request):
    all_date = Article.objects.all()
    context = {"all_date": all_date}

    return render(request, "articles/index.html", context)


def create(request):
    if request.method == "POST":
        form = MakeArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "글이 작성 완료!")

        return redirect("articles:index")
    else:
        form = MakeArticleForm()
    context = {"form": form}

    return render(request, "articles/create.html", context)


def edit(request, pk):
    pick_data = Article.objects.get(pk=pk)
    if request.method == "POST":
        form = MakeArticleForm(request.POST, request.FILES, instance=pick_data)
        if form.is_valid():
            form.save()
            messages.success(request, "글이 수정 완료!")
        return redirect("articles:detail", pick_data.pk)
    else:
        form = MakeArticleForm(instance=pick_data)
    context = {
        "form": form,
        "pick_data": pick_data,
    }

    return render(request, "articles/edit.html", context)


def detail(request, pk):
    detail_data = Article.objects.get(pk=pk)

    context = {"detail_data": detail_data}

    return render(request, "articles/detail.html", context)


def delete(reuqest, pk):
    Article.objects.get(pk=pk).delete()
    return redirect("articles:index")

Django/221017/221017/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<H1> 게시판 글 쓰기 </H1>

<form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% load static %}
    {% load django_bootstrap5 %}

    {% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="작성완료" %}
</form>

{% endblock %}

Django/221017/221017/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<H1>글 제목 : {{detail_data.title}} </H1>
<p>내용 : {{detail_data.content}}</p>

<p>작성시간{{detail_data.created_at}}</p>


{%if detail_data.img %}
<img width="400" height="300" src="{{detail_data.img.url}}" alt="{{detail_data.img}}">

{%endif%}

{%load django_bootstrap5 %}
<div>
    <a class="btn btn-primary" href="{% url 'articles:delete' detail_data.pk %}">삭제</a>
    <a class="btn btn-primary" href="{% url 'articles:edit' detail_data.pk %}">수정</a>
    <a class="btn btn-primary" href="{% url 'articles:index' %}">돌아가기</a>

</div>




{% endblock %}

Django/221017/221017/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
<H1> 게시판 수정 </H1>

<form action="{% url 'articles:edit' pick_data.pk  %}" method="POST" enctype="multipart/form-data">
    {% load static %}
    {% csrf_token %}
    {% load django_bootstrap5 %}

    {% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="작성완료" %} </form>

{% endblock %}

Django/221017/221017/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content%}

{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    {% if message.tags %} class="{{ message.tags }}" {% endif %}>
    {{ message }}{% endfor %}

</div>




</ul>
{% endif %}

<h1>게시판 인덱스 페이지</h1>

<a class="btn btn-primary" href="{% url 'articles:create' %}">새글쓰기</a>

<hr>

<div class="d-flex row">
    {% for article in all_date %}

    {% if article.img %}

    <div class="card col-4 m-5" style="width: 18rem;">
        <img src="{{ article.img.url }}" class="card-img-top" alt="{{articles.img.url}}">
        <div class="card-body">
            <h5 class="card-title">{{article.title}}</h5>
            <p class="card-text">{{article.content}}</p>
            <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">내용보기</a>
        </div>
    </div>


    {%else%}
    <div class="card col-4 m-5" style="width: 18rem;">
        <img src="" class="card-img-top" alt="{{articles.img.url}}">
        <div class="card-body">
            <h5 class="card-title">{{article.title}}</h5>
            <p class="card-text">{{article.content}}</p>
            <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">내용보기</a>
        </div>
    </div>


    {%endif%}

    {% endfor %}
</div>
{% endblock %}

Django/221017/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<H1> 게시판 글 쓰기 </H1>

<form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% load static %}
    {% load django_bootstrap5 %}

    {% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="작성완료" %}
</form>

{% endblock %}

Django/221017/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<H1>글 제목 : {{detail_data.title}} </H1>
<p>내용 : {{detail_data.content}}</p>

<p>작성시간{{detail_data.created_at}}</p>


{%if detail_data.img %}
<img width="400" height="300" src="{{detail_data.img.url}}" alt="{{detail_data.img}}">

{%endif%}

{%load django_bootstrap5 %}
<div>
    <a class="btn btn-primary" href="{% url 'articles:delete' detail_data.pk %}">삭제</a>
    <a class="btn btn-primary" href="{% url 'articles:edit' detail_data.pk %}">수정</a>
    <a class="btn btn-primary" href="{% url 'articles:index' %}">돌아가기</a>

</div>




{% endblock %}

Django/221017/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
<H1> 게시판 수정 </H1>

<form action="{% url 'articles:edit' pick_data.pk  %}" method="POST" enctype="multipart/form-data">
    {% load static %}
    {% csrf_token %}
    {% load django_bootstrap5 %}

    {% bootstrap_form form %}

    {% bootstrap_button button_type="submit" content="작성완료" %} </form>

{% endblock %}

Django/221017/articles/templates/articles/index.html
{% extends "base.html" %}

{% block content%}

{% if messages %}
{% for message in messages %}
<div class="alert alert-success" role="alert">
    {% if message.tags %} class="{{ message.tags }}" {% endif %}>
    {{ message }}{% endfor %}

</div>


{% endif %}

<h1>게시판 인덱스 페이지</h1>

<a class="btn btn-primary" href="{% url 'articles:create' %}">새글쓰기</a>

<hr>

<div class="d-flex row">
    {% for article in all_date %}

    {% if article.img %}

    <div class="card col-4 m-5" style="width: 18rem;">
        <img src="{{ article.img.url }}" class="card-img-top" alt="{{articles.img.url}}">
        <div class="card-body">
            <h5 class="card-title">{{article.title}}</h5>
            <p class="card-text">{{article.content}}</p>
            <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">내용보기</a>
        </div>
    </div>


    {%else%}
    <div class="card col-4 m-5" style="width: 18rem;">
        <img src="" class="card-img-top" alt="{{articles.img.url}}">
        <div class="card-body">
            <h5 class="card-title">{{article.title}}</h5>
            <p class="card-text">{{article.content}}</p>
            <a href="{% url 'articles:detail' article.pk %}" class="btn btn-primary">내용보기</a>
        </div>
    </div>


    {%endif%}

    {% endfor %}
</div>
{% endblock %}